let stockProductos = [
    {id: 1, nombre: "Velador Espiraldo Mod7", tipo: "deco", cantidad: 1, desc: "Velador Espiralado. Varios colores disponibles.", precio: 1900, img: 'assets/velador-blanco-modelo7.jpeg'},
    {id: 2, nombre: "Velador Espiraldo Mod3", tipo: "deco", cantidad: 1, desc: "Velador Espiralado. Varios colores disponibles.", precio: 1900, img: 'assets/velador-fucsia-modelo3.jpeg'},
    {id: 3, nombre: "Velador Espiraldo Mod33", tipo: "deco", cantidad: 1, desc: "Velador Espiralado. Varios colores disponibles.", precio: 1900, img: 'assets/velador-naranja-modelo33.jpeg'},
    {id: 4, nombre: "Velador Espiraldo Mod5", tipo: "deco", cantidad: 1, desc: "Velador Espiralado. Varios colores disponibles.", precio: 1900, img: 'assets/velador-on-azul-modelo5.jpeg'},
    {id: 5, nombre: "Juego didáctico", tipo: "juego", cantidad: 1, desc: "Ideal para ejercitar la parte motriz de los chicos. Juego de equilibrio. La base a medida es redonda y hace que al poner las piezas empiece a balancearse, hay que lograr poner todas las piezas sin que se caiga. Al que se le cae pierde!", precio: 1200, img: 'assets/tetrix-balancin.jpeg'},
    {id: 6, nombre: "Soportes Notebook", tipo: "soportes", cantidad: 1, esc: "Ideal para largas jornadas de trabajo frente a nuestra computadora, permite mejorar la postura y así evitar dolores cervicales y de espalda. Brinda la posibilidad de ajustar el ángulo de inclinación y mejorar la refrigeración del equipo. Además de ser encastrable lo que lo vuelve muy compacto y fácil de transportar. El soporte es plegable y se puede configurar en cuatro posiciones, 15 ° (7cm), 25 ° (10cm), 35 ° (12,5cm ) y 45 ° (15cm). Acepta notebooks de hasta 2cm de grosor (medir solo grosor de teclado). Disponibles en varios colores.", precio: 1200, img: '../assets/soportenotebook.jpg'},
    {id: 7, nombre: "Llavero soporte celular", tipo: "soportes", cantidad: 1, desc: "Varios diseños y colores.", precio: 250, img: 'assets/llaveros-soporte-celulares.jpeg'},
    {id: 8, nombre: "Pulpo articulado", tipo: "juego", cantidad: 1, desc: "Varios diseños y colores, incluso puede ser un llavero simpático.", precio: 250, img: 'assets/pulpoarticulado.jpg'},
    {id: 9, nombre: "Lapiceros personalizados", tipo: "lapiceros", cantidad: 1, desc: "Varios diseños y colores.", precio: 1800, img: 'assets/lapicero-mojo-gris.jpeg'},
    {id: 10, nombre: "Homero + dona", tipo: "deco", cantidad: 1, desc: "Decorá tus paredes. Varios diseños y colores.", precio: 500, img: 'assets/deco-homero-dona.jpeg'},
    {id: 11, nombre: "Flander", tipo: "deco", cantidad: 1, desc: "Decorá tus paredes. Varios diseños y colores.", precio: 500, img: "assets/deco-flander.jpg" }

]